---
title       : First Deck
subtitle    : Slidify + Shiny
author      : Jennifer Yueh
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light     # 
widgets     : [mathjax, bootstrap, quiz, shiny, interactive]  
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
ext_widgets : {rCharts: [libraries/nvd3]}
--- &radio

## Interactive Quiz

What is 1 + 1?

1. 1
2. _2_
3. 3
4. 4

*** .hint

This is a hint

*** .explanation

This is how it should be done


--- .class #id 

## Slide 2

Here is a math symbol:
$x^2$

---

## Slide 3

```{r, echo=FALSE}
data(mtcars)
head(mtcars, 5)
nrow(mtcars)
```

---

## Interactive Chart

```{r, echo=FALSE, results='asis'}
require(rCharts)

haireye <- as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = "Eye", type = "multiBarChart", data= subset(haireye, Sex=="Male"))
n1$print("chart1")
```
                                                                             

---
